"use client";

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type LanguageCode =
  | "de"
  | "en"
  | "ro"
  | "tr"
  | "fr"
  | "es"
  | "ar"
  | "pt"
  | "ru"
  | "pl"
  | "uk";

const SUPPORTED: LanguageCode[] = ["de", "en", "ro", "tr", "fr", "es", "ar", "pt", "ru", "pl", "uk"];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    home: "Home",
    files: "Files",
    needsAttentionTitle: "Needs your attention",
    needsAttentionSubtitle: "Documents with open tasks or deadlines.",
    readyTitle: "Swipe right to file",
    readySubtitle: "Documents without open tasks.",
    titleHeader: "Title",
    summaryHeader: "Summary",
    actionsHeader: "To-dos",
    loading: "Loading...",
    noDocs: "No documents yet.",
    noDocsOpen: "No documents with open tasks.",
    noDocsReady: "No documents ready to file.",
    noDocsProcessing: "No documents currently processing.",
    noCategory: "Uncategorized",
    noTasks: "No tasks",
    delete: "Delete",
    preview: "Preview",
    send: "Send",
    logout: "Log out",
    explainDocument: "Ask about this document",
    openOriginalDocument: "Open original document",
    filesAssistantIntro:
      "Galaxy gives you an overview of your documents. It can merge, calculate, and organize information across multiple documents. If something is missing, Galaxy will ask for it.",
    filesAssistantPlaceholder: "Question about all documents…",
    filesAssistantLoadSessionError: "Could not load session.",
    filesAssistantMissingSession: "No session found. Please sign in again.",
    filesAssistantUnavailable: "Assistant unavailable",
    filesAssistantPromptLabel: "Assistant prompt",
    selectFolder: "Select folder",
    chooseHere: "Choose here",
    allFolders: "All folders",
    back: "Back",
    noSubfolders: "No subfolders.",
    openTasks: "{count} open task",
    openTasksPlural: "{count} open tasks",
    noActionRequired: "No action required",
    actionRequired: "Action required",
    infoOnly: "Info only",
    showDetails: "Show details",
    hideDetails: "Hide details",
    details: "Details",
    copy: "Copy",
    copied: "Copied",
    detailsKeyFacts: "Key facts",
    detailsReference: "Reference",
    detailsContact: "Contact",
    detailsLabelBillingPeriod: "Billing period",
    detailsNoteBillingPeriod: "what this document covers",
    detailsLabelAmountTotal: "Total",
    detailsLabelDocumentDate: "Document date",
    detailsLabelDueDate: "Due date",
    detailsLabelDirectDebit: "Direct debit",
    detailsLabelAppealBy: "Appeal by",
    detailsLabelObjectionBy: "Object by",
    detailsLabelDeadline: "Deadline",
    detailsLabelPaidDate: "Paid",
    detailsNotePaid: "already paid",
    detailsNoteDirectDebit: "money leaves your bank",
    detailsNoteAppealOptional: "only if something is wrong",
    detailsLabelOrderDate: "Order date",
    detailsLabelMonthlyAmount: "Monthly payout",
    detailsNoteMonthlyAmount: "expected monthly payment",
    detailsLabelDailyRate: "Daily rate",
    detailsNoteDailyRate: "used to calculate payments",
    detailsLabelFollowUp: "Follow-up",
    detailsPrefixFrom: "from",
    detailsLabelContactPerson: "Contact",
    detailsLabelContactPhone: "Phone",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "New task",
    taskTitleLabel: "Title",
    taskDueDateLabel: "Due date",
    taskPlaceholder: "What needs to be done?",
    completed: "Completed ({count})",
    addTask: "Add task",
    cancel: "Cancel",
    urgency: "Urgency",
    low: "Low",
    normal: "Normal",
    high: "High",
    moveToFiles: "Move to files",
    applySuggestion: "Apply suggestion",
    suggestionLabel: "Suggested:",
    reprocess: "Reprocess",
    reprocessHint: "Re-run extraction",
    uploadDrop: "Drop files here or click to choose",
    uploadUploading: "Uploading...",
    uploadProcessing: "Processing upload...",
    scan: "Scan",
    scanTitle: "Scan a document",
    scanHint: "Use your camera to capture a document. Hold steady; we will crop it.",
    scanCapture: "Capture scan",
    scanError: "Camera unavailable. Please allow access or use file upload instead.",
    scanNotSupported: "Camera not supported in this browser. Please upload a file.",
    scanDone: "Done ({count})",
    scanPageSingular: "page",
    scanPagePlural: "pages",
    scanHoldStill: "Hold still",
    scanAlignPage: "Fit the page in the frame",
    scanTooDark: "Too dark",
    scanGlare: "Glare",
    scanBlurry: "Blurry — retake",
    scanLowContrast: "Low contrast",
    scanBadCrop: "Page not fully in frame",
    scanNoEdges: "Page not detected",
    scanGateFail: "Scan quality too low",
    scanGateBlur: "Too blurry",
    scanTorch: "Torch",
    scanTorchSuggest: "Turn on torch?",
    scanAuto: "Auto",
    scanOn: "On",
    scanOff: "Off",
    scanRetake: "Retake",
    scanRetakePending: "Retake next page…",
    scanCrop: "Crop",
    scanAddMore: "Scan more pages",
    scanSaveAsOne: "Save as 1 document",
    scanSaveTitle: "Title",
    scanSaveAndProcess: "Save & process",
    scanEnhance: "Enhancement",
    scanEnhanceThisPage: "This page",
    scanPresetAll: "All pages",
    scanPresetOcr: "OCR",
    scanPresetGray: "Grayscale",
    scanPresetColor: "Color",
    scanReorder: "Reorder",
    scanPageLabel: "Page {n}",
    scanQualityOk: "Looks good",
    scanQualityWarn: "Check quality",
    scanEditPage: "Edit page",
    scanApply: "Apply",
    scanCropHandle: "Resize crop",
    scanReset: "Reset",
    scanSplit: "Split",
    fileLabel: "Select",
    processingLong: "Processing is taking longer than usual - you can keep waiting or refresh later.",
    processingLongAction: "Refresh",
    processingTitle: "Processing",
    uploadHint: "PDF, DOC/DOCX, TXT, PNG, or JPEG. Max 25MB; images are optimized before upload.",
    pageCapToast: "This app doesn't process documents over {count} pages.",
    paste: "Paste",
    unsupportedType: "Unsupported file type. Please upload PDF, DOC, DOCX, TXT, PNG, or JPEG.",
    fileTooLarge: "File is too large. Please keep uploads under 25MB.",
    imageTooLarge: "Image is too large after processing. Please use a smaller image.",
    loginRequired: "You must be logged in to upload.",
    maxFiles: "Please upload up to {count} files at a time.",
    batchTooLarge: "Total upload too large. Please upload a smaller batch.",
    notLoggedIn: "Not logged in.",
    takingTooLong: "Taking too long to load documents. Please retry.",
    uncategorized: "Uncategorized",
    actionNeededBy: "Action needed by {date}",
    dueOverdue: "Deadline passed ({days} days)",
    dueToday: "Due today",
    dueInOne: "Due in 1 day",
    dueInDays: "Due in {days} days",
  },
  de: {
    home: "Home",
    files: "Ablage",
    needsAttentionTitle: "Benötigt deine Aufmerksamkeit",
    needsAttentionSubtitle: "Dokumente mit offenen Aufgaben oder Fristen.",
    readyTitle: "Ablagebereit",
    readySubtitle: "Dokumente ohne offene Aufgaben.",
    titleHeader: "Titel",
    summaryHeader: "Zusammenfassung",
    actionsHeader: "Aufgaben",
    loading: "Lade...",
    noDocs: "Noch keine Dokumente.",
    noDocsOpen: "Keine Dokumente mit offenen Aufgaben.",
    noDocsReady: "Keine dokumente fertig zur Ablage.",
    noDocsProcessing: "Keine Dokumente in Bearbeitung.",
    noCategory: "Ohne Kategorie",
    noTasks: "Keine Aufgaben",
    delete: "Löschen",
    preview: "Vorschau",
    send: "Senden",
    logout: "Abmelden",
    explainDocument: "Fragen zum Dokument",
    openOriginalDocument: "Original öffnen",
    filesAssistantIntro:
      "Galaxy verschafft dir Überblick über deine Dokumente. Es kann Informationen aus mehreren Dokumenten zusammenführen, berechnen und ordnen. Fehlt etwas, fragt Galaxy gezielt nach.",
    filesAssistantPlaceholder: "Frage über alle Dokumente…",
    filesAssistantLoadSessionError: "Konnte Sitzung nicht laden.",
    filesAssistantMissingSession: "Keine Sitzung gefunden. Bitte neu anmelden.",
    filesAssistantUnavailable: "Assistant momentan nicht verfügbar",
    filesAssistantPromptLabel: "Assistant-Eingabe",
    selectFolder: "Ordner auswählen",
    chooseHere: "Hier auswählen",
    allFolders: "Alle Ordner",
    back: "Zurück",
    noSubfolders: "Keine Unterordner.",
    openTasks: "{count} offene Aufgabe",
    openTasksPlural: "{count} offene Aufgaben",
    noActionRequired: "Kein Handlungsbedarf",
    actionRequired: "Handlung erforderlich",
    infoOnly: "Info only",
    showDetails: "Details anzeigen",
    hideDetails: "Details ausblenden",
    details: "Details",
    copy: "Kopieren",
    copied: "Kopiert",
    detailsKeyFacts: "Eckdaten",
    detailsReference: "Referenz",
    detailsContact: "Kontakt",
    detailsLabelBillingPeriod: "Abrechnungszeitraum",
    detailsNoteBillingPeriod: "worauf sich das Schreiben bezieht",
    detailsLabelAmountTotal: "Gesamtbetrag",
    detailsLabelDocumentDate: "Dokumentdatum",
    detailsLabelDueDate: "Fällig am",
    detailsLabelDirectDebit: "Lastschrift",
    detailsLabelAppealBy: "Einspruch bis",
    detailsLabelObjectionBy: "Widerspruch bis",
    detailsLabelDeadline: "Frist",
    detailsLabelPaidDate: "Bezahlt am",
    detailsNotePaid: "schon bezahlt",
    detailsNoteDirectDebit: "wird abgebucht",
    detailsNoteAppealOptional: "nur wenn etwas falsch ist",
    detailsLabelOrderDate: "Bestelldatum",
    detailsLabelMonthlyAmount: "Monatszahlung",
    detailsNoteMonthlyAmount: "voraussichtliche Monatszahlung",
    detailsLabelDailyRate: "Tagessatz",
    detailsNoteDailyRate: "Basis für die Berechnung",
    detailsLabelFollowUp: "Folgeschritt",
    detailsPrefixFrom: "ab",
    detailsLabelContactPerson: "Kontakt",
    detailsLabelContactPhone: "Telefon",
    detailsLabelContactEmail: "E-Mail",
    newTaskTitle: "Neue Aufgabe",
    taskTitleLabel: "Titel",
    taskDueDateLabel: "Fällig am",
    taskPlaceholder: "Was ist zu tun?",
    completed: "Erledigt ({count})",
    addTask: "Aufgabe hinzufügen",
    cancel: "Abbrechen",
    urgency: "Dringlichkeit",
    low: "Niedrig",
    normal: "Normal",
    high: "Hoch",
    moveToFiles: "Ablage",
    applySuggestion: "Vorschlag übernehmen",
    suggestionLabel: "Vorgeschlagen:",
    reprocess: "Neu verarbeiten",
    reprocessHint: "Extraktion erneut ausführen",
    uploadDrop: "Dateien hier ablegen oder klicken",
    uploadUploading: "Lade hoch...",
    uploadProcessing: "Verarbeitung läuft...",
    scan: "Scannen",
    scanTitle: "Dokument scannen",
    scanHint: "Kamera nutzen, ruhig halten - wir schneiden automatisch zu.",
    scanCapture: "Scan aufnehmen",
    scanError: "Kamera nicht verfügbar. Zugriff erlauben oder Datei hochladen.",
    scanNotSupported: "Kamera wird von diesem Browser nicht unterstützt. Bitte Datei hochladen.",
    scanDone: "Fertig ({count})",
    scanPageSingular: "Seite",
    scanPagePlural: "Seiten",
    scanHoldStill: "Bitte still halten",
    scanAlignPage: "Seite ins Bild bringen",
    scanTooDark: "Zu dunkel",
    scanGlare: "Reflexion",
    scanBlurry: "Unscharf, bitte neu.",
    scanLowContrast: "Zu wenig Kontrast",
    scanBadCrop: "Seite nicht vollständig im Bild",
    scanNoEdges: "Seite nicht erkannt",
    scanGateFail: "Qualität zu niedrig",
    scanGateBlur: "Zu unscharf",
    scanTorch: "Blitz",
    scanTorchSuggest: "Blitz einschalten?",
    scanAuto: "Auto",
    scanOn: "An",
    scanOff: "Aus",
    scanRetake: "Neu aufnehmen",
    scanRetakePending: "Nächste Aufnahme ersetzt…",
    scanCrop: "Zuschneiden",
    scanAddMore: "Weitere Seite scannen",
    scanSaveAsOne: "Als 1 Dokument speichern",
    scanSaveTitle: "Titel",
    scanSaveAndProcess: "Speichern & verarbeiten",
    scanEnhance: "Verbesserung",
    scanEnhanceThisPage: "Diese Seite",
    scanPresetAll: "Alle Seiten",
    scanPresetOcr: "OCR",
    scanPresetGray: "Graustufen",
    scanPresetColor: "Farbe",
    scanReorder: "Reihenfolge ändern",
    scanPageLabel: "Seite {n}",
    scanQualityOk: "Sieht gut aus",
    scanQualityWarn: "Qualität prüfen",
    scanEditPage: "Seite bearbeiten",
    scanApply: "Übernehmen",
    scanCropHandle: "Zuschneiden anpassen",
    scanReset: "Zurücksetzen",
    scanSplit: "Teilen",
    fileLabel: "Auswählen",
    processingLong: "Verarbeitung dauert länger als üblich - du kannst weiter warten oder später aktualisieren.",
    processingLongAction: "Aktualisieren",
    processingTitle: "Wird bearbeitet",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG oder JPEG. Max. 25MB; Bilder werden vor dem Upload optimiert.",
    pageCapToast: "Diese App verarbeitet keine Dokumente mit mehr als {count} Seiten.",
    paste: "Einfügen",
    unsupportedType:
      "Dateityp nicht unterstützt. Bitte lade PDF, DOC, DOCX, TXT, PNG oder JPEG hoch.",
    fileTooLarge: "Datei zu groß. Bitte unter 25MB bleiben.",
    imageTooLarge: "Bild nach Verarbeitung zu groß. Bitte kleineres Bild nutzen.",
    loginRequired: "Zum Hochladen anmelden.",
    maxFiles: "Bitte höchstens {count} Dateien auf einmal.",
    batchTooLarge: "Gesamt-Upload zu groß. Bitte kleinere Auswahl.",
    notLoggedIn: "Nicht eingeloggt.",
    takingTooLong: "Laden dauert zu lange. Bitte erneut versuchen.",
    uncategorized: "Ohne Kategorie",
    actionNeededBy: "Aktion benötigt bis {date}",
    dueOverdue: "Frist abgelaufen ({days} Tage)",
    dueToday: "Frist heute",
    dueInOne: "Frist in 1 Tag",
    dueInDays: "Frist in {days} Tagen",
  },
  ro: {
    home: "Acasă",
    files: "Arhivă",
    needsAttentionTitle: "Necesită atenție",
    needsAttentionSubtitle: "Documente cu sarcini sau termene.",
    readyTitle: "Gata de arhivare",
    readySubtitle: "Documente fără sarcini deschise.",
    titleHeader: "Titlu",
    summaryHeader: "Rezumat",
    actionsHeader: "Sarcini",
    loading: "Se încarcă...",
    noDocs: "Nu există documente.",
    noDocsOpen: "Nu există documente cu sarcini deschise.",
    noDocsReady: "Nu există documente gata de arhivare.",
    noDocsProcessing: "Niciun document în procesare.",
    noCategory: "Fără categorie",
    noTasks: "Nicio sarcină",
    delete: "Șterge",
    preview: "Previzualizare",
    send: "Trimite",
    logout: "Delogare",
    explainDocument: "Întrebări despre document",
    openOriginalDocument: "Deschide documentul original",
    filesAssistantIntro:
      "Galaxy îți oferă o vedere de ansamblu asupra documentelor tale. Poate să unească informații din mai multe fișiere, să calculeze și să le organizeze. Dacă lipsește ceva, Galaxy va întreba punctual.",
    filesAssistantPlaceholder: "Întrebare despre toate documentele…",
    filesAssistantLoadSessionError: "Nu am putut încărca sesiunea.",
    filesAssistantMissingSession: "Nu am găsit sesiune. Autentifică-te din nou.",
    filesAssistantUnavailable: "Asistent indisponibil",
    filesAssistantPromptLabel: "Prompt asistent",
    selectFolder: "Alege folder",
    chooseHere: "Alege aici",
    allFolders: "Toate folderele",
    back: "Înapoi",
    noSubfolders: "Fără subfoldere.",
    openTasks: "{count} sarcină deschisă",
    openTasksPlural: "{count} sarcini deschise",
    noActionRequired: "Nicio acțiune necesară",
    actionRequired: "Acțiune necesară",
    infoOnly: "Doar informare",
    showDetails: "Arată detalii",
    hideDetails: "Ascunde detalii",
    details: "Detalii",
    copy: "Copiază",
    copied: "Copiat",
    detailsKeyFacts: "Date cheie",
    detailsReference: "Referințe",
    detailsContact: "Contact",
    detailsLabelBillingPeriod: "Perioadă",
    detailsNoteBillingPeriod: "la ce se referă documentul",
    detailsLabelAmountTotal: "Total",
    detailsLabelDocumentDate: "Data documentului",
    detailsLabelDueDate: "Scadență",
    detailsLabelDirectDebit: "Debit direct",
    detailsLabelAppealBy: "Contestă până la",
    detailsLabelObjectionBy: "Obiecție până la",
    detailsLabelDeadline: "Termen",
    detailsLabelPaidDate: "Plătit la",
    detailsNotePaid: "deja plătit",
    detailsNoteDirectDebit: "se va debita din cont",
    detailsNoteAppealOptional: "doar dacă ceva este greșit",
    detailsLabelOrderDate: "Data comenzii",
    detailsLabelMonthlyAmount: "Plată lunară",
    detailsNoteMonthlyAmount: "plata lunară estimată",
    detailsLabelDailyRate: "Plată zilnică",
    detailsNoteDailyRate: "folosită la calcul",
    detailsLabelFollowUp: "Urmare",
    detailsPrefixFrom: "de la",
    detailsLabelContactPerson: "Contact",
    detailsLabelContactPhone: "Telefon",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Sarcină nouă",
    taskTitleLabel: "Titlu",
    taskDueDateLabel: "Termen",
    taskPlaceholder: "Ce trebuie făcut?",
    completed: "Finalizat ({count})",
    addTask: "Adaugă sarcină",
    cancel: "Anulează",
    urgency: "Prioritate",
    low: "Scăzută",
    normal: "Normală",
    high: "Ridicată",
    moveToFiles: "Arhivează",
    applySuggestion: "Aplică sugestia",
    suggestionLabel: "Sugerat:",
    reprocess: "Reprocesează",
    reprocessHint: "Rulează din nou extragerea",
    uploadDrop: "Trage fișierele aici sau click pentru a alege",
    uploadUploading: "Se încarcă...",
    uploadProcessing: "Se procesează...",
    scan: "scanare",
    scanTitle: "Scanează un document",
    scanHint: "Folosește camera și ține stabil; vom decupa automat.",
    scanCapture: "Capturează scanarea",
    scanError: "Camera nu este disponibilă. Permite accesul sau încarcă un fișier.",
    scanNotSupported: "Camera nu este suportată în acest browser. Încarcă un fișier.",
    fileLabel: "Selectează",
    processingLong: "Procesarea durează mai mult decât de obicei - poți aștepta sau reîmprospăta mai târziu.",
    processingLongAction: "Reîmprospătează",
    processingTitle: "Se procesează",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG sau JPEG. Max 25MB; imaginile sunt optimizate înainte de upload.",
    paste: "lipire",
    unsupportedType:
      "Tip de fișier neacceptat. Încarcă PDF, DOC, DOCX, TXT, PNG sau JPEG.",
    fileTooLarge: "Fișier prea mare. Limita este 25MB.",
    imageTooLarge: "Imagine prea mare după procesare. Folosește una mai mică.",
    loginRequired: "Trebuie să fii autentificat pentru a încărca.",
    maxFiles: "Încarcă maximum {count} fișiere odată.",
    batchTooLarge: "Setul de fișiere este prea mare. Folosește un lot mai mic.",
    notLoggedIn: "Neautentificat.",
    takingTooLong: "Se încarcă prea mult. Încearcă din nou.",
    uncategorized: "Fără categorie",
    actionNeededBy: "Acțiune necesară până la {date}",
    dueOverdue: "Termen depășit ({days} zile)",
    dueToday: "Termen azi",
    dueInOne: "Termen în 1 zi",
    dueInDays: "Termen în {days} zile",
  },
  tr: {
    home: "Ana sayfa",
    files: "Arşiv",
    needsAttentionTitle: "Dikkat gerekenler",
    needsAttentionSubtitle: "Açık görev veya son tarih içeren belgeler.",
    readyTitle: "Arşive hazır",
    readySubtitle: "Açık görevi olmayan belgeler.",
    titleHeader: "Başlık",
    summaryHeader: "Özet",
    actionsHeader: "Yapılacaklar",
    loading: "Yükleniyor...",
    noDocs: "Henüz belge yok.",
    noDocsOpen: "Açık görevli belge yok.",
    noDocsReady: "Arşive hazır belge yok.",
    noDocsProcessing: "Şu anda işlenen belge yok.",
    noCategory: "Kategori yok",
    noTasks: "Görev yok",
    delete: "Sil",
    preview: "Önizleme",
    send: "Gönder",
    logout: "Çıkış yap",
    explainDocument: "Belgeyle ilgili sorular",
    openOriginalDocument: "Orijinal belgeyi aç",
    filesAssistantIntro:
      "Galaxy belgelerin için genel bir bakış sağlar. Birden çok dosyadaki bilgileri birleştirir, hesaplar ve düzenler. Bir şey eksikse, Galaxy bunu özellikle sorar.",
    filesAssistantPlaceholder: "Tüm belgeler hakkında soru…",
    filesAssistantLoadSessionError: "Oturum yüklenemedi.",
    filesAssistantMissingSession: "Oturum bulunamadı. Lütfen tekrar giriş yap.",
    filesAssistantUnavailable: "Asistan kullanılamıyor",
    filesAssistantPromptLabel: "Asistan girişi",
    selectFolder: "Klasör seç",
    chooseHere: "Burayı seç",
    allFolders: "Tüm klasörler",
    back: "Geri",
    noSubfolders: "Alt klasör yok.",
    openTasks: "{count} açık görev",
    openTasksPlural: "{count} açık görev",
    noActionRequired: "İşlem gerekmez",
    actionRequired: "İşlem gerekli",
    infoOnly: "Sadece bilgi",
    showDetails: "Detayları göster",
    hideDetails: "Detayları gizle",
    details: "Detaylar",
    copy: "Kopyala",
    copied: "Kopyalandı",
    detailsKeyFacts: "Önemli bilgiler",
    detailsReference: "Referans",
    detailsContact: "İletişim",
    detailsLabelBillingPeriod: "Dönem",
    detailsNoteBillingPeriod: "belgenin kapsadığı dönem",
    detailsLabelAmountTotal: "Toplam",
    detailsLabelDocumentDate: "Belge tarihi",
    detailsLabelDueDate: "Son tarih",
    detailsLabelDirectDebit: "Otomatik ödeme",
    detailsLabelAppealBy: "İtiraz için son tarih",
    detailsLabelObjectionBy: "İtiraz için son tarih",
    detailsLabelDeadline: "Son tarih",
    detailsLabelPaidDate: "Ödeme tarihi",
    detailsNotePaid: "zaten ödendi",
    detailsNoteDirectDebit: "hesabından çekilecek",
    detailsNoteAppealOptional: "sadece yanlışsa",
    detailsLabelOrderDate: "Sipariş tarihi",
    detailsLabelMonthlyAmount: "Aylık ödeme",
    detailsNoteMonthlyAmount: "beklenen aylık ödeme",
    detailsLabelDailyRate: "Günlük tutar",
    detailsNoteDailyRate: "hesaplamada kullanılır",
    detailsLabelFollowUp: "Takip",
    detailsPrefixFrom: "itibaren",
    detailsLabelContactPerson: "İletişim",
    detailsLabelContactPhone: "Telefon",
    detailsLabelContactEmail: "E-posta",
    newTaskTitle: "Yeni görev",
    taskTitleLabel: "Başlık",
    taskDueDateLabel: "Son tarih",
    taskPlaceholder: "Ne yapılmalı?",
    completed: "Tamamlandı ({count})",
    addTask: "Görev ekle",
    cancel: "İptal",
    urgency: "Öncelik",
    low: "Düşük",
    normal: "Normal",
    high: "Yüksek",
    moveToFiles: "Arşive taşı",
    applySuggestion: "Öneriyi uygula",
    suggestionLabel: "Öneri:",
    reprocess: "Yeniden işle",
    reprocessHint: "Çıkarımı yeniden çalıştır",
    uploadDrop: "Dosyaları bırak veya tıkla",
    uploadUploading: "Yükleniyor...",
    uploadProcessing: "İşleniyor...",
    scan: "tara",
    scanTitle: "Belge tara",
    scanHint: "Kamerayı kullan, sabit tut; otomatik kırpıyoruz.",
    scanCapture: "Taramayı çek",
    scanError: "Kamera kullanılamıyor. Erişime izin ver veya dosya yükle.",
    scanNotSupported: "Kamera bu tarayıcıda desteklenmiyor. Lütfen dosya yükle.",
    fileLabel: "Seç",
    processingLong: "İşleme alışılmadık şekilde uzun sürüyor - bekleyebilir veya sonra yenileyebilirsin.",
    processingLongAction: "Yenile",
    processingTitle: "İşleniyor",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG veya JPEG. En fazla 25MB; görseller yüklemeden önce optimize edilir.",
    paste: "yapıştır",
    unsupportedType: "Desteklenmeyen dosya türü. PDF, DOC, DOCX, TXT, PNG veya JPEG yükleyin.",
    fileTooLarge: "Dosya çok büyük. 25MB altı olmalı.",
    imageTooLarge: "İşlem sonrası görsel çok büyük. Daha küçük bir görsel kullanın.",
    loginRequired: "Yüklemek için giriş yapmalısın.",
    maxFiles: "Bir seferde en fazla {count} dosya yükleyin.",
    batchTooLarge: "Toplam yükleme çok büyük. Daha küçük bir set yükleyin.",
    notLoggedIn: "Giriş yapılmadı.",
    takingTooLong: "Yükleme çok uzun sürdü. Yeniden deneyin.",
    uncategorized: "Kategorisiz",
    actionNeededBy: "{date} tarihine kadar işlem gerekli",
    dueOverdue: "Süre doldu ({days} gün)",
    dueToday: "Son tarih bugün",
    dueInOne: "Son tarih 1 gün içinde",
    dueInDays: "Son tarih {days} gün içinde",
  },
  fr: {
    home: "Accueil",
    files: "Archives",
    needsAttentionTitle: "À traiter",
    needsAttentionSubtitle: "Documents avec tâches ou échéances.",
    readyTitle: "Prêt à archiver",
    readySubtitle: "Documents sans tâches ouvertes.",
    titleHeader: "Titre",
    summaryHeader: "Résumé",
    actionsHeader: "Tâches",
    loading: "Chargement...",
    noDocs: "Aucun document.",
    noDocsOpen: "Aucun document avec tâches ouvertes.",
    noDocsReady: "Aucun document prêt à archiver.",
    noDocsProcessing: "Aucun document en cours de traitement.",
    noCategory: "Sans catégorie",
    noTasks: "Aucune tâche",
    delete: "Supprimer",
    preview: "Aperçu",
    send: "Envoyer",
    logout: "Se déconnecter",
    explainDocument: "Questions sur ce document",
    openOriginalDocument: "Ouvrir le document original",
    filesAssistantIntro:
      "Galaxy t’offre une vue d’ensemble de tes documents. Il peut fusionner, calculer et organiser des informations issues de plusieurs fichiers. S’il manque quelque chose, Galaxy le demandera clairement.",
    filesAssistantPlaceholder: "Question sur tous les documents…",
    filesAssistantLoadSessionError: "Impossible de charger la session.",
    filesAssistantMissingSession: "Aucune session trouvée. Merci de te reconnecter.",
    filesAssistantUnavailable: "Assistant indisponible",
    filesAssistantPromptLabel: "Invite assistant",
    selectFolder: "Choisir un dossier",
    chooseHere: "Choisir ici",
    allFolders: "Tous les dossiers",
    back: "Retour",
    noSubfolders: "Aucun sous-dossier.",
    openTasks: "{count} tâche ouverte",
    openTasksPlural: "{count} tâches ouvertes",
    noActionRequired: "Aucune action requise",
    actionRequired: "Action requise",
    infoOnly: "Info uniquement",
    showDetails: "Afficher les détails",
    hideDetails: "Masquer les détails",
    details: "Détails",
    copy: "Copier",
    copied: "Copié",
    detailsKeyFacts: "Faits clés",
    detailsReference: "Références",
    detailsContact: "Contact",
    detailsLabelBillingPeriod: "Période",
    detailsNoteBillingPeriod: "ce que couvre ce document",
    detailsLabelAmountTotal: "Total",
    detailsLabelDocumentDate: "Date du document",
    detailsLabelDueDate: "Échéance",
    detailsLabelDirectDebit: "Prélèvement",
    detailsLabelAppealBy: "Recours avant",
    detailsLabelObjectionBy: "Opposition avant",
    detailsLabelDeadline: "Échéance",
    detailsLabelPaidDate: "Payé le",
    detailsNotePaid: "déjà payé",
    detailsNoteDirectDebit: "sera prélevé",
    detailsNoteAppealOptional: "uniquement si erreur",
    detailsLabelOrderDate: "Date de commande",
    detailsLabelMonthlyAmount: "Montant mensuel",
    detailsNoteMonthlyAmount: "paiement mensuel prévu",
    detailsLabelDailyRate: "Taux journalier",
    detailsNoteDailyRate: "sert au calcul",
    detailsLabelFollowUp: "Suivi",
    detailsPrefixFrom: "à partir du",
    detailsLabelContactPerson: "Contact",
    detailsLabelContactPhone: "Téléphone",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Nouvelle tâche",
    taskTitleLabel: "Titre",
    taskDueDateLabel: "Date d'échéance",
    taskPlaceholder: "Que faut-il faire ?",
    completed: "Terminé ({count})",
    addTask: "Ajouter une tâche",
    cancel: "Annuler",
    urgency: "Priorité",
    low: "Basse",
    normal: "Normale",
    high: "Haute",
    moveToFiles: "Archiver",
    applySuggestion: "Appliquer la suggestion",
    suggestionLabel: "Suggéré :",
    reprocess: "Re-traiter",
    reprocessHint: "Relancer l'extraction",
    uploadDrop: "Déposez des fichiers ou cliquez pour choisir",
    uploadUploading: "Téléversement...",
    uploadProcessing: "Traitement en cours...",
    scan: "scanner",
    scanTitle: "Scanner un document",
    scanHint: "Utilise la caméra et reste stable ; nous cadrons automatiquement.",
    scanCapture: "Capturer",
    scanError: "Caméra indisponible. Autorise l'accès ou téléverse un fichier.",
    scanNotSupported: "Caméra non supportée par ce navigateur. Téléverse un fichier.",
    fileLabel: "Sélectionner",
    processingLong: "Le traitement prend plus de temps que d'habitude - vous pouvez attendre ou actualiser plus tard.",
    processingLongAction: "Actualiser",
    processingTitle: "Traitement en cours",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG ou JPEG. Max 25Mo; les images sont optimisées avant upload.",
    paste: "coller",
    unsupportedType:
      "Type de fichier non supporté. Téléversez PDF, DOC, DOCX, TXT, PNG ou JPEG.",
    fileTooLarge: "Fichier trop volumineux. Limite 25Mo.",
    imageTooLarge: "Image trop grande après traitement. Utilisez-en une plus petite.",
    loginRequired: "Connectez-vous pour téléverser.",
    maxFiles: "Téléversez au maximum {count} fichiers à la fois.",
    batchTooLarge: "Lot trop volumineux. Choisissez un lot plus petit.",
    notLoggedIn: "Non connecté.",
    takingTooLong: "Trop long. Réessayez.",
    uncategorized: "Sans catégorie",
    actionNeededBy: "Action requise avant le {date}",
    dueOverdue: "Échéance dépassée ({days} jours)",
    dueToday: "Échéance aujourd'hui",
    dueInOne: "Échéance dans 1 jour",
    dueInDays: "Échéance dans {days} jours",
  },
  es: {
    home: "Inicio",
    files: "Archivo",
    needsAttentionTitle: "Requiere atención",
    needsAttentionSubtitle: "Documentos con tareas o plazos.",
    readyTitle: "Listo para archivar",
    readySubtitle: "Documentos sin tareas pendientes.",
    titleHeader: "Título",
    summaryHeader: "Resumen",
    actionsHeader: "Tareas",
    loading: "Cargando...",
    noDocs: "Sin documentos.",
    noDocsOpen: "Sin documentos con tareas abiertas.",
    noDocsReady: "Sin documentos listos para archivar.",
    noDocsProcessing: "No hay documentos en proceso.",
    noCategory: "Sin categoría",
    noTasks: "Sin tareas",
    delete: "Eliminar",
    preview: "Vista previa",
    send: "Enviar",
    logout: "Cerrar sesión",
    explainDocument: "Perguntas sobre este documento",
    openOriginalDocument: "Abrir documento original",
    filesAssistantIntro:
      "Galaxy te da una visión general de tus documentos. Puede combinar, calcular y organizar información de varios archivos. Si falta algo, Galaxy lo pedirá de forma directa.",
    filesAssistantPlaceholder: "Pregunta sobre todos los documentos…",
    filesAssistantLoadSessionError: "No se pudo cargar la sesión.",
    filesAssistantMissingSession: "No se encontró sesión. Inicia sesión de nuevo.",
    filesAssistantUnavailable: "Asistente no disponible",
    filesAssistantPromptLabel: "Entrada del asistente",
    selectFolder: "Seleccionar carpeta",
    chooseHere: "Elegir aquí",
    allFolders: "Todas las carpetas",
    back: "Atrás",
    noSubfolders: "Sin subcarpetas.",
    openTasks: "{count} tarea abierta",
    openTasksPlural: "{count} tareas abiertas",
    noActionRequired: "Sin acción necesaria",
    actionRequired: "Acción necesaria",
    infoOnly: "Solo información",
    showDetails: "Mostrar detalles",
    hideDetails: "Ocultar detalles",
    details: "Detalles",
    copy: "Copiar",
    copied: "Copiado",
    detailsKeyFacts: "Datos clave",
    detailsReference: "Referencias",
    detailsContact: "Contacto",
    detailsLabelBillingPeriod: "Periodo",
    detailsNoteBillingPeriod: "a qué se refiere el documento",
    detailsLabelAmountTotal: "Total",
    detailsLabelDocumentDate: "Fecha del documento",
    detailsLabelDueDate: "Vencimiento",
    detailsLabelDirectDebit: "Domiciliación",
    detailsLabelAppealBy: "Recurso hasta",
    detailsLabelObjectionBy: "Reclamación hasta",
    detailsLabelDeadline: "Plazo",
    detailsLabelPaidDate: "Pagado el",
    detailsNotePaid: "ya pagado",
    detailsNoteDirectDebit: "se cargará en tu cuenta",
    detailsNoteAppealOptional: "solo si hay error",
    detailsLabelOrderDate: "Fecha de pedido",
    detailsLabelMonthlyAmount: "Pago mensual",
    detailsNoteMonthlyAmount: "pago mensual previsto",
    detailsLabelDailyRate: "Importe diario",
    detailsNoteDailyRate: "usado para el cálculo",
    detailsLabelFollowUp: "Seguimiento",
    detailsPrefixFrom: "desde",
    detailsLabelContactPerson: "Contacto",
    detailsLabelContactPhone: "Teléfono",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Nueva tarea",
    taskTitleLabel: "Título",
    taskDueDateLabel: "Fecha límite",
    taskPlaceholder: "¿Qué hay que hacer?",
    completed: "Completado ({count})",
    addTask: "Añadir tarea",
    cancel: "Cancelar",
    urgency: "Prioridad",
    low: "Baja",
    normal: "Normal",
    high: "Alta",
    moveToFiles: "Archivar",
    applySuggestion: "Aplicar sugerencia",
    suggestionLabel: "Sugerido:",
    reprocess: "Reprocesar",
    reprocessHint: "Ejecutar extracción de nuevo",
    uploadDrop: "Suelta archivos o haz clic para elegir",
    uploadUploading: "Subiendo...",
    uploadProcessing: "Procesando...",
    scan: "escanear",
    scanTitle: "Escanear un documento",
    scanHint: "Usa la cámara y mantén firme; recortamos automáticamente.",
    scanCapture: "Capturar escaneo",
    scanError: "Cámara no disponible. Permite acceso o sube un archivo.",
    scanNotSupported: "La cámara no es compatible en este navegador. Sube un archivo.",
    fileLabel: "Seleccionar",
    processingLong: "El procesamiento está tardando más de lo habitual - puedes seguir esperando o actualizar después.",
    processingLongAction: "Actualizar",
    processingTitle: "Procesando",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG o JPEG. Máx 25MB; las imágenes se optimizan antes de subir.",
    paste: "pegar",
    unsupportedType:
      "Tipo de archivo no soportado. Sube PDF, DOC, DOCX, TXT, PNG o JPEG.",
    fileTooLarge: "Archivo demasiado grande. Límite 25MB.",
    imageTooLarge: "Imagen demasiado grande tras procesar. Usa una más pequeña.",
    loginRequired: "Debes iniciar sesión para subir.",
    maxFiles: "Sube máximo {count} archivos a la vez.",
    batchTooLarge: "Lote demasiado grande. Usa uno más pequeño.",
    notLoggedIn: "No has iniciado sesión.",
    takingTooLong: "Tarda demasiado. Intenta de nuevo.",
    uncategorized: "Sin categoría",
    actionNeededBy: "Acción necesaria antes del {date}",
    dueOverdue: "Plazo vencido ({days} días)",
    dueToday: "Plazo hoy",
    dueInOne: "Plazo en 1 día",
    dueInDays: "Plazo en {days} días",
  },
  ar: {
    home: "الرئيسية",
    files: "الأرشيف",
    needsAttentionTitle: "بحاجة للانتباه",
    needsAttentionSubtitle: "رسائل بها مهام أو مواعيد نهائية.",
    readyTitle: "جاهز للأرشفة",
    readySubtitle: "رسائل بلا مهام مفتوحة.",
    titleHeader: "العنوان",
    summaryHeader: "الملخص",
    actionsHeader: "المهام",
    loading: "جارٍ التحميل...",
    noDocs: "لا توجد مستندات.",
    noDocsOpen: "لا توجد مستندات بها مهام مفتوحة.",
    noDocsReady: "لا توجد مستندات جاهزة للأرشفة.",
    noDocsProcessing: "لا توجد مستندات قيد المعالجة.",
    noCategory: "بدون فئة",
    noTasks: "لا مهام",
    delete: "حذف",
    preview: "معاينة",
    send: "إرسال",
    logout: "تسجيل الخروج",
    explainDocument: "أسئلة حول هذا المستند",
    openOriginalDocument: "افتح المستند الأصلي",
    filesAssistantIntro:
      "جالاكسي يمنحك نظرة شاملة على مستنداتك. يمكنه دمج المعلومات من عدة ملفات، حسابها وتنظيمها. إذا كان هناك نقص، سيطلب جالاكسي ذلك بشكل محدد.",
    filesAssistantPlaceholder: "سؤال حول كل المستندات…",
    filesAssistantLoadSessionError: "تعذّر تحميل الجلسة.",
    filesAssistantMissingSession: "لم يتم العثور على جلسة. يرجى تسجيل الدخول مرة أخرى.",
    filesAssistantUnavailable: "المساعد غير متاح",
    filesAssistantPromptLabel: "حقل المساعد",
    selectFolder: "اختر مجلداً",
    chooseHere: "اختر هنا",
    allFolders: "كل المجلدات",
    back: "رجوع",
    noSubfolders: "لا توجد مجلدات فرعية.",
    openTasks: "{count} مهمة مفتوحة",
    openTasksPlural: "{count} مهام مفتوحة",
    noActionRequired: "لا يلزم إجراء",
    actionRequired: "إجراء مطلوب",
    infoOnly: "معلومة فقط",
    showDetails: "إظهار التفاصيل",
    hideDetails: "إخفاء التفاصيل",
    details: "التفاصيل",
    copy: "نسخ",
    copied: "تم النسخ",
    detailsKeyFacts: "معلومات أساسية",
    detailsReference: "مرجع",
    detailsContact: "جهة الاتصال",
    detailsLabelBillingPeriod: "فترة الفوترة",
    detailsNoteBillingPeriod: "ما يغطيه المستند",
    detailsLabelAmountTotal: "الإجمالي",
    detailsLabelDocumentDate: "تاريخ المستند",
    detailsLabelDueDate: "تاريخ الاستحقاق",
    detailsLabelDirectDebit: "سحب مباشر",
    detailsLabelAppealBy: "تظلم حتى",
    detailsLabelObjectionBy: "اعتراض حتى",
    detailsLabelDeadline: "الموعد النهائي",
    detailsLabelPaidDate: "مدفوع في",
    detailsNotePaid: "مدفوع بالفعل",
    detailsNoteDirectDebit: "سيتم الخصم من حسابك",
    detailsNoteAppealOptional: "فقط إذا كان هناك خطأ",
    detailsLabelOrderDate: "تاريخ الطلب",
    detailsLabelMonthlyAmount: "مبلغ شهري",
    detailsNoteMonthlyAmount: "الدفعة الشهرية المتوقعة",
    detailsLabelDailyRate: "معدل يومي",
    detailsNoteDailyRate: "يستخدم للحساب",
    detailsLabelFollowUp: "متابعة",
    detailsPrefixFrom: "من",
    detailsLabelContactPerson: "جهة الاتصال",
    detailsLabelContactPhone: "هاتف",
    detailsLabelContactEmail: "بريد إلكتروني",
    newTaskTitle: "مهمة جديدة",
    taskTitleLabel: "العنوان",
    taskDueDateLabel: "تاريخ الاستحقاق",
    taskPlaceholder: "ما العمل؟",
    completed: "مكتمل ({count})",
    addTask: "إضافة مهمة",
    cancel: "إلغاء",
    urgency: "الأولوية",
    low: "منخفض",
    normal: "عادي",
    high: "مرتفع",
    moveToFiles: "أرشفة",
    applySuggestion: "تطبيق الاقتراح",
    suggestionLabel: "مقترح:",
    reprocess: "إعادة المعالجة",
    reprocessHint: "إعادة تشغيل الاستخراج",
    uploadDrop: "اسحب الملفات هنا أو اضغط للاختيار",
    uploadUploading: "جارٍ الرفع...",
    uploadProcessing: "جارٍ المعالجة...",
    scan: "مسح",
    scanTitle: "مسح مستند",
    scanHint: "استخدم الكاميرا وثبت الهاتف؛ سنقص الصورة تلقائيًا.",
    scanCapture: "التقاط المسح",
    scanError: "الكاميرا غير متاحة. اسمح بالوصول أو ارفع ملفًا.",
    scanNotSupported: "الكاميرا غير مدعومة في هذا المتصفح. من فضلك ارفع ملفًا.",
    fileLabel: "اختيار",
    processingLong: "المعالجة تستغرق وقتًا أطول من المعتاد - يمكنك الانتظار أو التحديث لاحقًا.",
    processingLongAction: "تحديث",
    processingTitle: "جارٍ المعالجة",
    uploadHint: "PDF أو DOC/DOCX أو TXT أو PNG أو JPEG. الحد 25MB؛ يتم تحسين الصور قبل الرفع.",
    paste: "لصق",
    unsupportedType: "نوع ملف غير مدعوم. ارفع PDF أو DOC أو DOCX أو TXT أو PNG أو JPEG.",
    fileTooLarge: "الملف كبير جدًا. الحد 25MB.",
    imageTooLarge: "الصورة كبيرة بعد المعالجة. استخدم صورة أصغر.",
    loginRequired: "يجب تسجيل الدخول للرفع.",
    maxFiles: "حمّل حتى {count} ملفات في المرة الواحدة.",
    batchTooLarge: "الحزمة كبيرة جدًا. استخدم حزمة أصغر.",
    notLoggedIn: "غير مسجل الدخول.",
    takingTooLong: "يستغرق وقتًا طويلاً. حاول مرة أخرى.",
    uncategorized: "بدون فئة",
    actionNeededBy: "إجراء مطلوب قبل {date}",
    dueOverdue: "انتهى الموعد ({days} أيام)",
    dueToday: "الموعد اليوم",
    dueInOne: "الموعد خلال يوم",
    dueInDays: "الموعد خلال {days} أيام",
  },
  pt: {
    home: "Início",
    files: "Arquivo",
    needsAttentionTitle: "Requer atenção",
    needsAttentionSubtitle: "Documentos com tarefas ou prazos.",
    readyTitle: "Pronto para arquivar",
    readySubtitle: "Documentos sem tarefas abertas.",
    titleHeader: "Título",
    summaryHeader: "Resumo",
    actionsHeader: "A fazer",
    loading: "Carregando...",
    noDocs: "Nenhum documento.",
    noDocsOpen: "Nenhum documento com tarefas abertas.",
    noDocsReady: "Nenhum documento pronto para arquivar.",
    noDocsProcessing: "Nenhum documento em processamento.",
    noCategory: "Sem categoria",
    noTasks: "Sem tarefas",
    delete: "Excluir",
    preview: "Pré-visualizar",
    send: "Enviar",
    logout: "Sair",
    explainDocument: "Perguntas sobre este documento",
    openOriginalDocument: "Abrir documento original",
    filesAssistantIntro:
      "A Galaxy dá-te visão sobre os teus documentos. Consegue juntar, calcular e organizar informação de vários ficheiros. Se faltar algo, a Galaxy pergunta de forma direta.",
    filesAssistantPlaceholder: "Pergunta sobre todos os documentos…",
    filesAssistantLoadSessionError: "Não foi possível carregar a sessão.",
    filesAssistantMissingSession: "Sessão não encontrada. Faça login novamente.",
    filesAssistantUnavailable: "Assistente indisponível",
    filesAssistantPromptLabel: "Prompt do assistente",
    selectFolder: "Selecionar pasta",
    chooseHere: "Escolher aqui",
    allFolders: "Todas as pastas",
    back: "Voltar",
    noSubfolders: "Sem subpastas.",
    openTasks: "{count} tarefa aberta",
    openTasksPlural: "{count} tarefas abertas",
    noActionRequired: "Nenhuma ação necessária",
    actionRequired: "Ação necessária",
    infoOnly: "Apenas informação",
    showDetails: "Mostrar detalhes",
    hideDetails: "Ocultar detalhes",
    details: "Detalhes",
    copy: "Copiar",
    copied: "Copiado",
    detailsKeyFacts: "Dados principais",
    detailsReference: "Referência",
    detailsContact: "Contacto",
    detailsLabelBillingPeriod: "Período",
    detailsNoteBillingPeriod: "o que este documento cobre",
    detailsLabelAmountTotal: "Total",
    detailsLabelDocumentDate: "Data do documento",
    detailsLabelDueDate: "Vencimento",
    detailsLabelDirectDebit: "Débito direto",
    detailsLabelAppealBy: "Recurso até",
    detailsLabelObjectionBy: "Oposição até",
    detailsLabelDeadline: "Prazo",
    detailsLabelPaidDate: "Pago em",
    detailsNotePaid: "já pago",
    detailsNoteDirectDebit: "será debitado da conta",
    detailsNoteAppealOptional: "apenas se houver erro",
    detailsLabelOrderDate: "Data do pedido",
    detailsLabelMonthlyAmount: "Pagamento mensal",
    detailsNoteMonthlyAmount: "pagamento mensal previsto",
    detailsLabelDailyRate: "Valor diário",
    detailsNoteDailyRate: "usado no cálculo",
    detailsLabelFollowUp: "Seguimento",
    detailsPrefixFrom: "a partir de",
    detailsLabelContactPerson: "Contacto",
    detailsLabelContactPhone: "Telefone",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Nova tarefa",
    taskTitleLabel: "Título",
    taskDueDateLabel: "Vencimento",
    taskPlaceholder: "O que precisa ser feito?",
    completed: "Concluído ({count})",
    addTask: "Adicionar tarefa",
    cancel: "Cancelar",
    urgency: "Prioridade",
    low: "Baixa",
    normal: "Normal",
    high: "Alta",
    moveToFiles: "Arquivar",
    applySuggestion: "Aplicar sugestão",
    suggestionLabel: "Sugerido:",
    reprocess: "Reprocessar",
    reprocessHint: "Executar a extração novamente",
    uploadDrop: "Solte arquivos aqui ou clique para escolher",
    uploadUploading: "Enviando...",
    uploadProcessing: "Processando...",
    scan: "escanear",
    scanTitle: "Digitalizar documento",
    scanHint: "Use a câmera e mantenha firme; recortamos automaticamente.",
    scanCapture: "Capturar digitalização",
    scanError: "Câmera indisponível. Permita acesso ou envie um arquivo.",
    scanNotSupported: "Câmera não suportada neste navegador. Envie um arquivo.",
    fileLabel: "Selecionar",
    processingLong:
      "O processamento está demorando mais que o normal - você pode esperar ou atualizar depois.",
    processingLongAction: "Atualizar",
    processingTitle: "Processando",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG ou JPEG. Máx 25MB; imagens são otimizadas antes do envio.",
    paste: "colar",
    unsupportedType: "Tipo de arquivo não suportado. Envie PDF, DOC, DOCX, TXT, PNG ou JPEG.",
    fileTooLarge: "Arquivo muito grande. Limite de 25MB.",
    imageTooLarge: "Imagem grande demais após o processamento. Use uma menor.",
    loginRequired: "Faça login para enviar.",
    maxFiles: "Envie até {count} arquivos por vez.",
    batchTooLarge: "Lote muito grande. Use um menor.",
    notLoggedIn: "Não conectado.",
    takingTooLong: "Demorando demais. Tente novamente.",
    uncategorized: "Sem categoria",
    actionNeededBy: "Ação necessária até {date}",
    dueOverdue: "Prazo vencido ({days} dias)",
    dueToday: "Prazo hoje",
    dueInOne: "Prazo em 1 dia",
    dueInDays: "Prazo em {days} dias",
  },
  ru: {
    home: "Главная",
    files: "Архив",
    needsAttentionTitle: "Требует внимания",
    needsAttentionSubtitle: "Документы с задачами или сроками.",
    readyTitle: "Готово к архиву",
    readySubtitle: "Документы без открытых задач.",
    titleHeader: "Название",
    summaryHeader: "Сводка",
    actionsHeader: "Задачи",
    loading: "Загрузка...",
    noDocs: "Документов нет.",
    noDocsOpen: "Нет документов с открытыми задачами.",
    noDocsReady: "Нет документов, готовых к архиву.",
    noDocsProcessing: "Нет документов в обработке.",
    noCategory: "Без категории",
    noTasks: "Нет задач",
    delete: "Удалить",
    preview: "Просмотр",
    send: "Отправить",
    logout: "Выйти",
    explainDocument: "Вопросы по этому документу",
    openOriginalDocument: "Открыть оригинал документа",
    filesAssistantIntro:
      "Galaxy дает обзор ваших документов. Она может объединять, рассчитывать и упорядочивать данные из нескольких файлов. Если чего-то не хватает, Galaxy уточнит это.",
    filesAssistantPlaceholder: "Вопрос по всем документам…",
    filesAssistantLoadSessionError: "Не удалось загрузить сессию.",
    filesAssistantMissingSession: "Сессия не найдена. Пожалуйста, войдите снова.",
    filesAssistantUnavailable: "Ассистент недоступен",
    filesAssistantPromptLabel: "Запрос ассистенту",
    selectFolder: "Выбрать папку",
    chooseHere: "Выбрать здесь",
    allFolders: "Все папки",
    back: "Назад",
    noSubfolders: "Нет вложенных папок.",
    openTasks: "{count} открытая задача",
    openTasksPlural: "{count} открытых задач",
    noActionRequired: "Действий не требуется",
    actionRequired: "Требуется действие",
    infoOnly: "Только информация",
    showDetails: "Показать детали",
    hideDetails: "Скрыть детали",
    details: "Детали",
    copy: "Копировать",
    copied: "Скопировано",
    detailsKeyFacts: "Ключевые факты",
    detailsReference: "Реквизиты",
    detailsContact: "Контакты",
    detailsLabelBillingPeriod: "Период",
    detailsNoteBillingPeriod: "что охватывает документ",
    detailsLabelAmountTotal: "Итого",
    detailsLabelDocumentDate: "Дата документа",
    detailsLabelDueDate: "Срок",
    detailsLabelDirectDebit: "Автосписание",
    detailsLabelAppealBy: "Обжаловать до",
    detailsLabelObjectionBy: "Возражение до",
    detailsLabelDeadline: "Срок",
    detailsLabelPaidDate: "Оплачено",
    detailsNotePaid: "уже оплачено",
    detailsNoteDirectDebit: "спишется со счета",
    detailsNoteAppealOptional: "только если есть ошибка",
    detailsLabelOrderDate: "Дата заказа",
    detailsLabelMonthlyAmount: "Ежемесячная выплата",
    detailsNoteMonthlyAmount: "ожидаемый месячный платеж",
    detailsLabelDailyRate: "Дневная ставка",
    detailsNoteDailyRate: "используется для расчета",
    detailsLabelFollowUp: "Последующее действие",
    detailsPrefixFrom: "с",
    detailsLabelContactPerson: "Контакт",
    detailsLabelContactPhone: "Телефон",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Новая задача",
    taskTitleLabel: "Заголовок",
    taskDueDateLabel: "Срок",
    taskPlaceholder: "Что нужно сделать?",
    completed: "Выполнено ({count})",
    addTask: "Добавить задачу",
    cancel: "Отмена",
    urgency: "Приоритет",
    low: "Низкий",
    normal: "Нормальный",
    high: "Высокий",
    moveToFiles: "В архив",
    applySuggestion: "Применить предложение",
    suggestionLabel: "Предложено:",
    reprocess: "Повторно обработать",
    reprocessHint: "Запустить извлечение еще раз",
    uploadDrop: "Перетащите файлы или нажмите, чтобы выбрать",
    uploadUploading: "Загрузка...",
    uploadProcessing: "Обработка...",
    scan: "сканировать",
    scanTitle: "Сканировать документ",
    scanHint: "Используй камеру и держи ровно; обрезка автоматически.",
    scanCapture: "Сделать снимок",
    scanError: "Камера недоступна. Разреши доступ или загрузи файл.",
    scanNotSupported: "Камера не поддерживается в этом браузере. Загрузите файл.",
    fileLabel: "Выбрать",
    processingLong:
      "Обработка занимает дольше обычного - можете подождать или обновить позже.",
    processingLongAction: "Обновить",
    processingTitle: "Обработка",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG или JPEG. До 25MB; изображения оптимизируются перед загрузкой.",
    paste: "вставить",
    unsupportedType:
      "Неподдерживаемый тип файла. Загрузите PDF, DOC, DOCX, TXT, PNG или JPEG.",
    fileTooLarge: "Файл слишком большой. Лимит 25MB.",
    imageTooLarge: "Изображение слишком большое после обработки. Используйте меньший файл.",
    loginRequired: "Войдите, чтобы загрузить.",
    maxFiles: "Загружайте до {count} файлов за раз.",
    batchTooLarge: "Пакет слишком большой. Используйте меньший.",
    notLoggedIn: "Не вошли в систему.",
    takingTooLong: "Слишком долго. Попробуйте снова.",
    uncategorized: "Без категории",
    actionNeededBy: "Действие требуется до {date}",
    dueOverdue: "Срок прошел ({days} дн.)",
    dueToday: "Срок сегодня",
    dueInOne: "Срок через 1 день",
    dueInDays: "Срок через {days} дней",
  },
  pl: {
    home: "Strona główna",
    files: "Archiwum",
    needsAttentionTitle: "Wymaga uwagi",
    needsAttentionSubtitle: "Dokumenty z zadaniami lub terminami.",
    readyTitle: "Gotowe do archiwizacji",
    readySubtitle: "Dokumenty bez otwartych zadań.",
    titleHeader: "Tytuł",
    summaryHeader: "Podsumowanie",
    actionsHeader: "Zadania",
    loading: "Ładowanie...",
    noDocs: "Brak dokumentów.",
    noDocsOpen: "Brak dokumentów z otwartymi zadaniami.",
    noDocsReady: "Brak dokumentów gotowych do archiwizacji.",
    noDocsProcessing: "Brak dokumentów w przetwarzaniu.",
    noCategory: "Bez kategorii",
    noTasks: "Brak zadań",
    delete: "Usuń",
    preview: "Podgląd",
    send: "Wyślij",
    logout: "Wyloguj się",
    explainDocument: "Pytania o ten dokument",
    openOriginalDocument: "Otwórz oryginalny dokument",
    filesAssistantIntro:
      "Galaxy daje wgląd w twoje dokumenty. Potrafi łączyć, liczyć i porządkować informacje z wielu plików. Jeśli czegoś brakuje, Galaxy o to zapyta wprost.",
    filesAssistantPlaceholder: "Pytanie o wszystkie dokumenty…",
    filesAssistantLoadSessionError: "Nie udało się wczytać sesji.",
    filesAssistantMissingSession: "Brak sesji. Zaloguj się ponownie.",
    filesAssistantUnavailable: "Asystent niedostępny",
    filesAssistantPromptLabel: "Pole asystenta",
    selectFolder: "Wybierz folder",
    chooseHere: "Wybierz tutaj",
    allFolders: "Wszystkie foldery",
    back: "Wstecz",
    noSubfolders: "Brak podfolderów.",
    openTasks: "{count} otwarte zadanie",
    openTasksPlural: "{count} otwartych zadań",
    noActionRequired: "Brak wymaganych działań",
    actionRequired: "Wymagane działanie",
    infoOnly: "Tylko informacja",
    showDetails: "Pokaż szczegóły",
    hideDetails: "Ukryj szczegóły",
    details: "Szczegóły",
    copy: "Kopiuj",
    copied: "Skopiowano",
    detailsKeyFacts: "Kluczowe fakty",
    detailsReference: "Referencje",
    detailsContact: "Kontakt",
    detailsLabelBillingPeriod: "Okres",
    detailsNoteBillingPeriod: "czego dotyczy dokument",
    detailsLabelAmountTotal: "Suma",
    detailsLabelDocumentDate: "Data dokumentu",
    detailsLabelDueDate: "Termin",
    detailsLabelDirectDebit: "Polecenie zapłaty",
    detailsLabelAppealBy: "Odwołanie do",
    detailsLabelObjectionBy: "Sprzeciw do",
    detailsLabelDeadline: "Termin",
    detailsLabelPaidDate: "Zapłacono",
    detailsNotePaid: "już zapłacono",
    detailsNoteDirectDebit: "zostanie pobrane z konta",
    detailsNoteAppealOptional: "tylko jeśli coś jest nie tak",
    detailsLabelOrderDate: "Data zamówienia",
    detailsLabelMonthlyAmount: "Płatność miesięczna",
    detailsNoteMonthlyAmount: "przewidywana płatność miesięczna",
    detailsLabelDailyRate: "Stawka dzienna",
    detailsNoteDailyRate: "używana do obliczeń",
    detailsLabelFollowUp: "Dalsze kroki",
    detailsPrefixFrom: "od",
    detailsLabelContactPerson: "Kontakt",
    detailsLabelContactPhone: "Telefon",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Nowe zadanie",
    taskTitleLabel: "Tytuł",
    taskDueDateLabel: "Termin",
    taskPlaceholder: "Co trzeba zrobić?",
    completed: "Ukończone ({count})",
    addTask: "Dodaj zadanie",
    cancel: "Anuluj",
    urgency: "Priorytet",
    low: "Niski",
    normal: "Normalny",
    high: "Wysoki",
    moveToFiles: "Archiwizuj",
    applySuggestion: "Zastosuj sugestię",
    suggestionLabel: "Sugestia:",
    reprocess: "Przetwórz ponownie",
    reprocessHint: "Uruchom ekstrakcję ponownie",
    uploadDrop: "Upuść pliki tutaj lub kliknij, aby wybrać",
    uploadUploading: "Przesyłanie...",
    uploadProcessing: "Przetwarzanie...",
    scan: "skanuj",
    scanTitle: "Skanuj dokument",
    scanHint: "Użyj aparatu i trzymaj stabilnie; automatycznie przytniemy.",
    scanCapture: "Zrób skan",
    scanError: "Kamera niedostępna. Zezwól na dostęp lub wyślij plik.",
    scanNotSupported: "Kamera nie jest obsługiwana w tej przeglądarce. Prześlij plik.",
    fileLabel: "Wybierz",
    processingLong:
      "Przetwarzanie trwa dłużej niż zwykle - możesz poczekać albo odświeżyć później.",
    processingLongAction: "Odśwież",
    processingTitle: "Przetwarzanie",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG lub JPEG. Maks 25MB; obrazy są optymalizowane przed wysłaniem.",
    paste: "wklej",
    unsupportedType:
      "Nieobsługiwany typ pliku. Prześlij PDF, DOC, DOCX, TXT, PNG lub JPEG.",
    fileTooLarge: "Plik jest za duży. Limit 25MB.",
    imageTooLarge: "Obraz jest zbyt duży po przetworzeniu. Użyj mniejszego.",
    loginRequired: "Zaloguj się, aby przesłać.",
    maxFiles: "Prześlij maksymalnie {count} plików na raz.",
    batchTooLarge: "Partia jest za duża. Użyj mniejszej.",
    notLoggedIn: "Nie jesteś zalogowany.",
    takingTooLong: "Za długo to trwa. Spróbuj ponownie.",
    uncategorized: "Bez kategorii",
    actionNeededBy: "Działanie wymagane do {date}",
    dueOverdue: "Termin minął ({days} dni)",
    dueToday: "Termin dzisiaj",
    dueInOne: "Termin za 1 dzień",
    dueInDays: "Termin za {days} dni",
  },
  uk: {
    home: "Головна",
    files: "Архів",
    needsAttentionTitle: "Потребує уваги",
    needsAttentionSubtitle: "Документи із завданнями або дедлайнами.",
    readyTitle: "Готово до архіву",
    readySubtitle: "Документи без відкритих завдань.",
    titleHeader: "Назва",
    summaryHeader: "Підсумок",
    actionsHeader: "Завдання",
    loading: "Завантаження...",
    noDocs: "Немає документів.",
    noDocsOpen: "Немає документів з відкритими завданнями.",
    noDocsReady: "Немає документів, готових до архіву.",
    noDocsProcessing: "Немає документів в обробці.",
    noCategory: "Без категорії",
    noTasks: "Немає завдань",
    delete: "Видалити",
    preview: "Перегляд",
    send: "Надіслати",
    logout: "Вийти",
    explainDocument: "Питання щодо цього документа",
    openOriginalDocument: "Відкрити оригінал документа",
    filesAssistantIntro:
      "Galaxy дає огляд твоїх документів. Вона може об’єднувати, рахувати та впорядковувати дані з кількох файлів. Якщо чогось бракує, Galaxy запитає про це конкретно.",
    filesAssistantPlaceholder: "Питання про всі документи…",
    filesAssistantLoadSessionError: "Не вдалося завантажити сесію.",
    filesAssistantMissingSession: "Сесію не знайдено. Будь ласка, увійдіть знову.",
    filesAssistantUnavailable: "Асистент недоступний",
    filesAssistantPromptLabel: "Запит асистенту",
    selectFolder: "Вибрати папку",
    chooseHere: "Вибрати тут",
    allFolders: "Усі папки",
    back: "Назад",
    noSubfolders: "Немає підпапок.",
    openTasks: "{count} відкрите завдання",
    openTasksPlural: "{count} відкритих завдань",
    noActionRequired: "Дій не потрібно",
    actionRequired: "Потрібна дія",
    infoOnly: "Лише інформація",
    showDetails: "Показати деталі",
    hideDetails: "Приховати деталі",
    details: "Деталі",
    copy: "Копіювати",
    copied: "Скопійовано",
    detailsKeyFacts: "Ключові факти",
    detailsReference: "Реквізити",
    detailsContact: "Контакти",
    detailsLabelBillingPeriod: "Період",
    detailsNoteBillingPeriod: "що охоплює документ",
    detailsLabelAmountTotal: "Сума",
    detailsLabelDocumentDate: "Дата документа",
    detailsLabelDueDate: "Термін",
    detailsLabelDirectDebit: "Автосписання",
    detailsLabelAppealBy: "Оскаржити до",
    detailsLabelObjectionBy: "Заперечення до",
    detailsLabelDeadline: "Дедлайн",
    detailsLabelPaidDate: "Оплачено",
    detailsNotePaid: "вже сплачено",
    detailsNoteDirectDebit: "спишеться з рахунку",
    detailsNoteAppealOptional: "лише якщо є помилка",
    detailsLabelOrderDate: "Дата замовлення",
    detailsLabelMonthlyAmount: "Щомісячна виплата",
    detailsNoteMonthlyAmount: "очікуваний щомісячний платіж",
    detailsLabelDailyRate: "Денна ставка",
    detailsNoteDailyRate: "використовується для розрахунку",
    detailsLabelFollowUp: "Подальші дії",
    detailsPrefixFrom: "з",
    detailsLabelContactPerson: "Контакт",
    detailsLabelContactPhone: "Телефон",
    detailsLabelContactEmail: "Email",
    newTaskTitle: "Нове завдання",
    taskTitleLabel: "Заголовок",
    taskDueDateLabel: "Термін",
    taskPlaceholder: "Що потрібно зробити?",
    completed: "Виконано ({count})",
    addTask: "Додати завдання",
    cancel: "Скасувати",
    urgency: "Пріоритет",
    low: "Низький",
    normal: "Звичайний",
    high: "Високий",
    moveToFiles: "В архів",
    applySuggestion: "Застосувати пропозицію",
    suggestionLabel: "Запропоновано:",
    reprocess: "Повторно обробити",
    reprocessHint: "Запустити витягнення ще раз",
    uploadDrop: "Перетягніть файли сюди або натисніть, щоб вибрати",
    uploadUploading: "Завантаження...",
    uploadProcessing: "Обробка...",
    scan: "сканувати",
    scanTitle: "Сканувати документ",
    scanHint: "Використовуйте камеру та тримайте рівно; ми автоматично обріжемо.",
    scanCapture: "Зробити скан",
    scanError: "Камера недоступна. Дозвольте доступ або завантажте файл.",
    scanNotSupported: "Камера не підтримується цим браузером. Завантажте файл.",
    fileLabel: "Вибрати",
    processingLong:
      "Обробка триває довше, ніж зазвичай - можна почекати або оновити пізніше.",
    processingLongAction: "Оновити",
    processingTitle: "Обробляється",
    uploadHint:
      "PDF, DOC/DOCX, TXT, PNG або JPEG. До 25MB; зображення оптимізуються перед завантаженням.",
    paste: "вставити",
    unsupportedType:
      "Непідтримуваний тип файлу. Завантажте PDF, DOC, DOCX, TXT, PNG або JPEG.",
    fileTooLarge: "Файл занадто великий. Обмеження 25MB.",
    imageTooLarge: "Зображення занадто велике після обробки. Використайте менше.",
    loginRequired: "Увійдіть, щоб завантажувати.",
    maxFiles: "Завантажуйте до {count} файлів за раз.",
    batchTooLarge: "Пакет завеликий. Використайте менший.",
    notLoggedIn: "Не увійшли.",
    takingTooLong: "Занадто довго. Спробуйте ще раз.",
    uncategorized: "Без категорії",
    actionNeededBy: "Дія потрібна до {date}",
    dueOverdue: "Термін минув ({days} днів)",
    dueToday: "Термін сьогодні",
    dueInOne: "Термін за 1 день",
    dueInDays: "Термін за {days} днів",
  },
};

const fallbackLang: LanguageCode = "en";

type Ctx = {
  lang: LanguageCode;
  setLang: (code: LanguageCode) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<Ctx | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LanguageCode>("de");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const stored = localStorage.getItem("docflow-lang");
    if (stored && SUPPORTED.includes(stored as LanguageCode)) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setLangState(stored as LanguageCode);
    }
  }, []);

  const updateLang = useCallback((code: LanguageCode) => {
    setLangState(code);
    if (typeof window !== "undefined") {
      localStorage.setItem("docflow-lang", code);
    }
  }, []);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const table = translations[lang] || translations[fallbackLang];
      const fallback = translations[fallbackLang][key] || key;
      let value = table[key] || fallback;
      if (vars) {
        Object.entries(vars).forEach(([k, v]) => {
          value = value.replace(`{${k}}`, String(v));
        });
      }
      return value;
    },
    [lang]
  );

  const ctx = useMemo(() => ({ lang, setLang: updateLang, t }), [lang, t, updateLang]);

  return <LanguageContext.Provider value={ctx}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): Ctx {
  const ctx = useContext(LanguageContext);
  if (ctx) return ctx;
  // Fallback to English if provider missing
  const t = (key: string, vars?: Record<string, string | number>) => {
    let value = translations[fallbackLang][key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        value = value.replace(`{${k}}`, String(v));
      });
    }
    return value;
  };
  return {
    lang: fallbackLang,
    setLang: () => {},
    t,
  };
}

export function isSupportedLanguage(code: string | null | undefined): code is LanguageCode {
  return !!code && SUPPORTED.includes(code as LanguageCode);
}

export function getLocaleForLanguage(code: LanguageCode): string {
  switch (code) {
    case "de":
      return "de-DE";
    case "ro":
      return "ro-RO";
    case "tr":
      return "tr-TR";
    case "fr":
      return "fr-FR";
    case "es":
      return "es-ES";
    case "ar":
      return "ar-EG";
    case "pt":
      return "pt-PT";
    case "ru":
      return "ru-RU";
    case "pl":
      return "pl-PL";
    case "uk":
      return "uk-UA";
    default:
      return "en-US";
  }
}
